######################################################################
#
# File name : sim1_compile.do
# Created on: Mon Jan 14 12:23:30 +0100 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_10.7c\\win64\\vlib questa_lib/work
C:\\questasim64_10.7c\\win64\\vlib questa_lib/msim

C:\\questasim64_10.7c\\win64\\vlib questa_lib/msim/xil_defaultlib

C:\\questasim64_10.7c\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

C:\\questasim64_10.7c\\win64\\vlog -64 -incr -dpiheader ../../../../firmware/driver/vc_hdrs.h -printinfilenames -work xil_defaultlib  "+incdir+../../../../simple_platform.srcs/sources_1/new" "+incdir+../../../../firmware/driver" "+incdir+C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../simple_platform.srcs/sources_1/imports/platform/camellia.v" \

C:\\questasim64_10.7c\\win64\\vlog -64 -incr -dpiheader ../../../../firmware/driver/vc_hdrs.h -printinfilenames -sv -L xil_defaultlib -work xil_defaultlib  "+incdir+../../../../simple_platform.srcs/sources_1/new" "+incdir+../../../../firmware/driver" "+incdir+C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../simple_platform.srcs/sources_1/new/buslayer_master.sv" \
"../../../../simple_platform.srcs/sources_1/new/buslayer_slave.sv" \
"../../../../simple_platform.srcs/sources_1/new/camellia_wrapper.v" \
"../../../../simple_platform.srcs/sources_1/new/core_wrapper.v" \
"../../../../simple_platform.srcs/sources_1/new/serial_transmitter.v" \
"../../../../simple_platform.srcs/sources_1/new/serial_transmitter_wrapper.v" \
"../../../../simple_platform.srcs/sources_1/new/simple_platform.sv" \
"../../../../simple_platform.srcs/sources_1/new/syscon.v" \
"../../../../simple_platform.srcs/sources_1/new/wishbone_bus.v" \
"../../../../simple_platform.srcs/sources_1/new/wishbone_bus_selector.v" \
"../../../../simple_platform.srcs/sim_1/new/sim1.v" \

# compile glbl module
C:\\questasim64_10.7c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

