######################################################################
#
# File name : sim1_elaborate.do
# Created on: Mon Jan 14 12:23:36 +0100 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_10.7c\\win64\\vopt -64 +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.sim1 xil_defaultlib.glbl -o sim1_opt

quit -force
