######################################################################
#
# File name : sim1_wave.do
# Created on: Sat Jan 12 12:52:26 +0100 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
