######################################################################
#
# File name : sim1_simulate.do
# Created on: Sun Jan 13 21:15:26 +0100 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib sim1_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {sim1_wave.do}

view wave
view structure
view signals

do {sim1.udo}

run 1000ns
