/* MTI_DPI */

/*
 * Copyright 2002-2019 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_VC_HDRS
#define INCLUDED_VC_HDRS

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
run_testbench();

DPI_LINK_DECL int
read_transaction(
    int addressIn,
    int byteSelIn,
    int* dataOut,
    char* errorOut);

DPI_LINK_DECL int
write_transaction(
    int addressIn,
    int dataIn,
    char byteSelIn,
    char* errorOut);

#endif 
